# Linea algebra

In [1]:
import torch

In [5]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x/y, x*y, x-y

(tensor([5.]), tensor([1.5000]), tensor([6.]), tensor([1.]))

In [10]:
float(x), x.item(), int(x)

(3.0, 3.0, 3)

# Vectors

In [14]:
x = torch.arange(5, dtype=torch.float)
x

tensor([0., 1., 2., 3., 4.])

In [18]:
x.shape, x.numel(), x.size()

(torch.Size([5]), 5, torch.Size([5]))

In [19]:
x = torch.arange(10, dtype=torch.float)
A = x.reshape(5,2)
A, x

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.],
         [8., 9.]]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [20]:
A.T

tensor([[0., 2., 4., 6., 8.],
        [1., 3., 5., 7., 9.]])

# Tensors

In [23]:
X = torch.arange(24, dtype=torch.float).reshape(2, 3, 4)
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [24]:
torch.ones(size = (4,))

tensor([1., 1., 1., 1.])

In [25]:
torch.zeros(size=(4,))

tensor([0., 0., 0., 0.])

In [28]:
torch.ones((4,3)).sum()

tensor(12.)

In [29]:
torch.ones((4,3)).sum(axis=1)

tensor([3., 3., 3., 3.])

In [30]:
torch.ones((4,3)).sum(axis=0)

tensor([4., 4., 4.])

In [31]:
torch.ones((4,3)).sum(axis=0, keepdims=True)

tensor([[4., 4., 4.]])

In [32]:
torch.ones((4,3)).sum(axis=1, keepdims=True)

tensor([[3.],
        [3.],
        [3.],
        [3.]])

In [38]:
torch.ones((4,3)).cumsum(dim=0)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [43]:
x = torch.rand((4,3))
x.mean(axis=0)

tensor([0.5847, 0.5947, 0.3377])

# Matrix operations

In [45]:
x = torch.arange(10)

In [46]:
x.dot(x)

tensor(285)

In [53]:
X = torch.arange(20).reshape(2, 10)

In [54]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
X

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [57]:
X.mv(x) # matrix vector multiplication

tensor([285, 735])

In [58]:
X * x

tensor([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81],
        [  0,  11,  24,  39,  56,  75,  96, 119, 144, 171]])

In [61]:
X.mm(X.T)

tensor([[ 285,  735],
        [ 735, 2185]])

# Norms

In [72]:
x = torch.arange(4) + 1.0

In [73]:
x.norm() # L2-Norm

tensor(5.4772)

In [75]:
x.abs().sum() # L1-Norme

tensor(10.)