# Getting started

In [1]:
import torch

Create a row vector x containing the first 12 integers starting with 0

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

We can access an ndarray's shape (the length along each axis) by inspecting its shape property

In [3]:
x.shape

torch.Size([12])

If we want to know the number of elemetns in an ndarray

In [16]:
x.numel()

12

## Reshapes use

reshape `(12,)` to `(3,4)`, it's no necessary to specify both dimension, if you know one dimension set the other equal to `-1` and will be inferred

In [5]:
# x = x.view(3, -1)
x = x.view(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
# x = x.view(-1, 4)
x = x.view(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

## Creating `ndarrays` methods

The empty method grabs a chunk of memory and hands us back a matrix without bothering to change the balue of any of its entries

In [7]:
torch.empty(size=(3,4))

tensor([[1.7792e-06, 4.5581e-41, 8.1422e-14, 3.0824e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.8788e+31, 1.7220e+22]])

Typically, we will want our matrices initialized either with zeros, ones, some other constants, or
numbers randomly sampled from a specific distribution. We can create an ndarray representing
a tensor with all elements set to 0 and a shape of `(2, 3, 4)` as follows:

In [8]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

similarly we can create tensors with each element set to $1$ as follows:

In [9]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We want to randomly sample the values for each element in an `ndarray`from som probability distribution. For example, when we construct arrays to serve as parameters in a neural network, we will typically initialize their values randomly

In [10]:
torch.normal(0, 1, (3,4))

tensor([[-0.7667, -0.1256, -0.7001,  2.7738],
        [ 2.7810, -0.4538, -0.3652,  0.0293],
        [ 0.3188,  0.6292,  1.5478, -0.9629]])

Create a normal `ndarray` specifying the exact values as a python list

In [11]:
torch.Tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

# Operations

## Element wise operations

In [12]:
x = torch.Tensor([1, 2, 4, 8])
y = torch.Tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Many more operations can be applied elementwise, including unary operators like exponentiation

In [13]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## `ndarrays` concatenation

In [35]:
x = torch.arange(12).view(3, -1)
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=x.dtype)
x.shape, y.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [36]:
torch.cat((x, y), 0), torch.cat((x, y), 1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

## Logical operations

In [37]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [38]:
x < y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [39]:
x[x < y], y[x < y]

(tensor([0, 2]), tensor([2, 4]))

In [40]:
x > y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [41]:
x[x > y], y[x > y]

(tensor([ 4,  5,  6,  7,  8,  9, 10, 11]), tensor([1, 2, 3, 4, 4, 3, 2, 1]))

## Operations along an axis

In [48]:
x.sum(), x.sum(axis=0), x.sum(axis=1)

(tensor(66), tensor([12, 15, 18, 21]), tensor([ 6, 22, 38]))

In [50]:
x.float().mean(), x.float().mean(axis=0), x.float().mean(axis=1)

(tensor(5.5000), tensor([4., 5., 6., 7.]), tensor([1.5000, 5.5000, 9.5000]))

# Broadcasting mechanism

Under certain conditions, even when shapes differ, we can still perform elementwise operations by invoking the broadcasting mechanism

In [59]:
a = torch.arange(3).view(3,1)
b = torch.arange(2).view(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [60]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In order to this broadcasting operation function the shapes need to share one dimension at least

In [61]:
a * b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [62]:
a = torch.arange(6).view(3,2,1)
b = torch.arange(2).view(1,1,2)
a, b

(tensor([[[0],
          [1]],
 
         [[2],
          [3]],
 
         [[4],
          [5]]]),
 tensor([[[0, 1]]]))

In [63]:
a + b

tensor([[[0, 1],
         [1, 2]],

        [[2, 3],
         [3, 4]],

        [[4, 5],
         [5, 6]]])

In [64]:
a = torch.arange(6).view(3,2)
b = torch.arange(2).view(1,2)
a, b

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 1]]))

In [65]:
a + b

tensor([[0, 2],
        [2, 4],
        [4, 6]])

In [66]:
a = torch.arange(6).view(3,2)
b = torch.arange(3).view(3,1)
a, b

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0],
         [1],
         [2]]))

In [67]:
a + b

tensor([[0, 1],
        [3, 4],
        [6, 7]])

# Indexing and slicing

The same as a python array

In [68]:
x[-1], x[1:3]

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [69]:
x[1,2]=9
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

Assingning to multiple indexes

In [70]:
x[0:2, :] = 12
x

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

# Saving in memory

Running operations can cause new memory to be allocated to host results

In [71]:
before = id(y)
y = y + x
id(y) == before

False

We need to perform operations and updates in place to save memory and time

In [72]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 139705346333824
id(z): 139705346333824


if the value of x is not reused in subsequent computations we can use

In [73]:
before = id(x)
x += y
id(x) == before

True

# Conversion to other python objects

In [76]:
a = x.numpy()
b = torch.tensor(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

To convert a size-one ndarray to a python scalar, we can use the `item` function

In [79]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)