# Scalars

Scalars in mxnet are just array with one element

In [1]:
from mxnet import np, npx
npx.set_np()

In [2]:
x = np.array(3.0)
y = np.array(2.0)

x+y, x*y, x/y, x**y

(array(5.), array(6.), array(1.5), array(9.))

# Vectors

In [3]:
x = np.arange(4)
x

array([0., 1., 2., 3.])

In [4]:
x[3]

array(3.)

## Length and Shape

## Lenght

In [5]:
len(x)

4

## Shape

In [6]:
x.shape

(4,)

# Matrices

In [7]:
A = np.arange(20).reshape(5,4)
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [8]:
B = np.ones_like(A)
B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Transpose matrix

In [9]:
A.T

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [10]:
A.T.T == A

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
A.T + B.T == (A + B).T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [12]:
A = np.arange(4).reshape(2,2)
(A + A.T) == (A + A.T).T 

array([[ True,  True],
       [ True,  True]])

## Symmetric matrix

In [13]:
B = np.array([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

array([[1., 2., 3.],
       [2., 0., 4.],
       [3., 4., 5.]])

In [14]:
B.T == B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Tensors

Data structures with more than two axes, generalize matrices

In [25]:
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [26]:
len(X) # Correspond of the lenght of axis = 0

2

In [27]:
X.shape

(2, 3, 4)

In [29]:
X.sum(axis=0).shape, X.sum(axis=1).shape, X.sum(axis=2).shape

((3, 4), (2, 4), (2, 3))

In [32]:
np.linalg.norm(X)

array(65.757126)

# Basic Properties of Tensor Arithmetic

## Element-wise sumation

In [18]:
A = np.arange(20).reshape(5,4)
B = A.copy() # Assign a copy of A to B by allocating new memory
A, A+B

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]),
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]))

In [24]:
A/A.sum(axis=1, keepdims=True)

array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]])

## Element-wise product

In [17]:
A*B # The hadamard product

array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]])

## Scalar operations with tensor

In [18]:
a = 2
X = np.arange(24).reshape(2, 3, 4)
a + X, a * X # It's operate a to each element of X

(array([[[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.]],
 
        [[14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.]]]),
 array([[[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.]],
 
        [[24., 26., 28., 30.],
         [32., 34., 36., 38.],
         [40., 42., 44., 46.]]]))

# Reduction

In [19]:
x = np.arange(4)
x, x.sum()

(array([0., 1., 2., 3.]), array(6.))

In [22]:
A.shape, A.sum() # sum all the values of the matrix

((5, 4), array(190.))

In [31]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(array([40., 45., 50., 55.]), (4,))

In [30]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(array([ 6., 22., 38., 54., 70.]), (5,))

In [26]:
A.sum(axis=[0, 1]) # Same as A.sum()

array(190.)

In [27]:
A.mean(), A.sum() / A.size # mean of all elements of A

(array(9.5), array(9.5))

In [28]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0] # mean along the axis 0

(array([ 8.,  9., 10., 11.]), array([ 8.,  9., 10., 11.]))

In [29]:
A.mean(axis=1), A.sum(axis=1) / A.shape[1] # mean along the axis 0

(array([ 1.5,  5.5,  9.5, 13.5, 17.5]), array([ 1.5,  5.5,  9.5, 13.5, 17.5]))

# Non reduction operations

However, sometimes it can be useful to keep the number of axes unchanged when invoking sum
or mean by setting `keepdims=True.`

In [32]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]])

In [33]:
A / sum_A # So we can use broadcasting

array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]])

In [34]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [36]:
A.cumsum(axis=0) # Cumulative sum along axis = 0

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]])

# Dot products

In [37]:
y = np.ones(4)
x, y, np.dot(x, y)

(array([0., 1., 2., 3.]), array([1., 1., 1., 1.]), array(6.))

In [38]:
np.sum(x * y) # the same dot product

array(6.)

# Matrix vector products

In [39]:
A.shape, x.shape, np.dot(A, x)

((5, 4), (4,), array([ 14.,  38.,  62.,  86., 110.]))

# Matrix-Matrix multiplications

In [40]:
B = np.ones(shape=(4, 3))
np.dot(A, B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

# Norms

In [42]:
# L2 norm
u = np.array([3, -4])
np.linalg.norm(u)

array(5.)

In [43]:
# L1 norm
np.abs(u).sum()

array(7.)

In [44]:
# Frobenious Norm
np.linalg.norm(np.ones((4,9)))

array(6.)